//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 07:39:09 PM IST 
//


package onix.social.logos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}EpubLicenseExpressionType"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}EpubLicenseExpressionTypeName" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}EpubLicenseExpressionLink"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="EpubLicenseExpression"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="epublicenseexpression"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "epubLicenseExpressionType",
    "epubLicenseExpressionTypeName",
    "epubLicenseExpressionLink"
})
@XmlRootElement(name = "EpubLicenseExpression")
public class EpubLicenseExpression {

    @XmlElement(name = "EpubLicenseExpressionType", required = true)
    protected EpubLicenseExpressionType epubLicenseExpressionType;
    @XmlElement(name = "EpubLicenseExpressionTypeName")
    protected EpubLicenseExpressionTypeName epubLicenseExpressionTypeName;
    @XmlElement(name = "EpubLicenseExpressionLink", required = true)
    protected EpubLicenseExpressionLink epubLicenseExpressionLink;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the epubLicenseExpressionType property.
     * 
     * @return
     *     possible object is
     *     {@link EpubLicenseExpressionType }
     *     
     */
    public EpubLicenseExpressionType getEpubLicenseExpressionType() {
        return epubLicenseExpressionType;
    }

    /**
     * Sets the value of the epubLicenseExpressionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpubLicenseExpressionType }
     *     
     */
    public void setEpubLicenseExpressionType(EpubLicenseExpressionType value) {
        this.epubLicenseExpressionType = value;
    }

    /**
     * Gets the value of the epubLicenseExpressionTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link EpubLicenseExpressionTypeName }
     *     
     */
    public EpubLicenseExpressionTypeName getEpubLicenseExpressionTypeName() {
        return epubLicenseExpressionTypeName;
    }

    /**
     * Sets the value of the epubLicenseExpressionTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpubLicenseExpressionTypeName }
     *     
     */
    public void setEpubLicenseExpressionTypeName(EpubLicenseExpressionTypeName value) {
        this.epubLicenseExpressionTypeName = value;
    }

    /**
     * Gets the value of the epubLicenseExpressionLink property.
     * 
     * @return
     *     possible object is
     *     {@link EpubLicenseExpressionLink }
     *     
     */
    public EpubLicenseExpressionLink getEpubLicenseExpressionLink() {
        return epubLicenseExpressionLink;
    }

    /**
     * Sets the value of the epubLicenseExpressionLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpubLicenseExpressionLink }
     *     
     */
    public void setEpubLicenseExpressionLink(EpubLicenseExpressionLink value) {
        this.epubLicenseExpressionLink = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
