//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 07:39:09 PM IST 
//


package onix.social.logos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List175.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List175">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A101"/>
 *     &lt;enumeration value="A102"/>
 *     &lt;enumeration value="A103"/>
 *     &lt;enumeration value="A104"/>
 *     &lt;enumeration value="A105"/>
 *     &lt;enumeration value="A106"/>
 *     &lt;enumeration value="A107"/>
 *     &lt;enumeration value="A108"/>
 *     &lt;enumeration value="A109"/>
 *     &lt;enumeration value="A110"/>
 *     &lt;enumeration value="A111"/>
 *     &lt;enumeration value="A112"/>
 *     &lt;enumeration value="A201"/>
 *     &lt;enumeration value="A202"/>
 *     &lt;enumeration value="A203"/>
 *     &lt;enumeration value="A204"/>
 *     &lt;enumeration value="A205"/>
 *     &lt;enumeration value="A206"/>
 *     &lt;enumeration value="A207"/>
 *     &lt;enumeration value="A208"/>
 *     &lt;enumeration value="A209"/>
 *     &lt;enumeration value="A210"/>
 *     &lt;enumeration value="A211"/>
 *     &lt;enumeration value="A212"/>
 *     &lt;enumeration value="A301"/>
 *     &lt;enumeration value="A302"/>
 *     &lt;enumeration value="A303"/>
 *     &lt;enumeration value="A304"/>
 *     &lt;enumeration value="A305"/>
 *     &lt;enumeration value="A410"/>
 *     &lt;enumeration value="A420"/>
 *     &lt;enumeration value="A421"/>
 *     &lt;enumeration value="A441"/>
 *     &lt;enumeration value="A451"/>
 *     &lt;enumeration value="B101"/>
 *     &lt;enumeration value="B102"/>
 *     &lt;enumeration value="B103"/>
 *     &lt;enumeration value="B104"/>
 *     &lt;enumeration value="B105"/>
 *     &lt;enumeration value="B106"/>
 *     &lt;enumeration value="B107"/>
 *     &lt;enumeration value="B108"/>
 *     &lt;enumeration value="B109"/>
 *     &lt;enumeration value="B110"/>
 *     &lt;enumeration value="B111"/>
 *     &lt;enumeration value="B112"/>
 *     &lt;enumeration value="B113"/>
 *     &lt;enumeration value="B114"/>
 *     &lt;enumeration value="B115"/>
 *     &lt;enumeration value="B116"/>
 *     &lt;enumeration value="B117"/>
 *     &lt;enumeration value="B118"/>
 *     &lt;enumeration value="B119"/>
 *     &lt;enumeration value="B120"/>
 *     &lt;enumeration value="B121"/>
 *     &lt;enumeration value="B122"/>
 *     &lt;enumeration value="B123"/>
 *     &lt;enumeration value="B124"/>
 *     &lt;enumeration value="B125"/>
 *     &lt;enumeration value="B126"/>
 *     &lt;enumeration value="B127"/>
 *     &lt;enumeration value="B128"/>
 *     &lt;enumeration value="B129"/>
 *     &lt;enumeration value="B130"/>
 *     &lt;enumeration value="B131"/>
 *     &lt;enumeration value="B201"/>
 *     &lt;enumeration value="B202"/>
 *     &lt;enumeration value="B204"/>
 *     &lt;enumeration value="B205"/>
 *     &lt;enumeration value="B206"/>
 *     &lt;enumeration value="B207"/>
 *     &lt;enumeration value="B208"/>
 *     &lt;enumeration value="B209"/>
 *     &lt;enumeration value="B210"/>
 *     &lt;enumeration value="B212"/>
 *     &lt;enumeration value="B213"/>
 *     &lt;enumeration value="B214"/>
 *     &lt;enumeration value="B215"/>
 *     &lt;enumeration value="B221"/>
 *     &lt;enumeration value="B222"/>
 *     &lt;enumeration value="B223"/>
 *     &lt;enumeration value="B301"/>
 *     &lt;enumeration value="B302"/>
 *     &lt;enumeration value="B303"/>
 *     &lt;enumeration value="B304"/>
 *     &lt;enumeration value="B305"/>
 *     &lt;enumeration value="B306"/>
 *     &lt;enumeration value="B307"/>
 *     &lt;enumeration value="B308"/>
 *     &lt;enumeration value="B309"/>
 *     &lt;enumeration value="B310"/>
 *     &lt;enumeration value="B311"/>
 *     &lt;enumeration value="B312"/>
 *     &lt;enumeration value="B313"/>
 *     &lt;enumeration value="B314"/>
 *     &lt;enumeration value="B315"/>
 *     &lt;enumeration value="B316"/>
 *     &lt;enumeration value="B317"/>
 *     &lt;enumeration value="B400"/>
 *     &lt;enumeration value="B401"/>
 *     &lt;enumeration value="B402"/>
 *     &lt;enumeration value="B403"/>
 *     &lt;enumeration value="B404"/>
 *     &lt;enumeration value="B405"/>
 *     &lt;enumeration value="B406"/>
 *     &lt;enumeration value="B409"/>
 *     &lt;enumeration value="B410"/>
 *     &lt;enumeration value="B411"/>
 *     &lt;enumeration value="B412"/>
 *     &lt;enumeration value="B413"/>
 *     &lt;enumeration value="B414"/>
 *     &lt;enumeration value="B415"/>
 *     &lt;enumeration value="B416"/>
 *     &lt;enumeration value="B501"/>
 *     &lt;enumeration value="B502"/>
 *     &lt;enumeration value="B503"/>
 *     &lt;enumeration value="B504"/>
 *     &lt;enumeration value="B505"/>
 *     &lt;enumeration value="B506"/>
 *     &lt;enumeration value="B507"/>
 *     &lt;enumeration value="B508"/>
 *     &lt;enumeration value="B509"/>
 *     &lt;enumeration value="B510"/>
 *     &lt;enumeration value="B511"/>
 *     &lt;enumeration value="B512"/>
 *     &lt;enumeration value="B513"/>
 *     &lt;enumeration value="B514"/>
 *     &lt;enumeration value="B515"/>
 *     &lt;enumeration value="B516"/>
 *     &lt;enumeration value="B601"/>
 *     &lt;enumeration value="B602"/>
 *     &lt;enumeration value="B610"/>
 *     &lt;enumeration value="B701"/>
 *     &lt;enumeration value="B702"/>
 *     &lt;enumeration value="B703"/>
 *     &lt;enumeration value="B704"/>
 *     &lt;enumeration value="B705"/>
 *     &lt;enumeration value="B706"/>
 *     &lt;enumeration value="B707"/>
 *     &lt;enumeration value="D101"/>
 *     &lt;enumeration value="D102"/>
 *     &lt;enumeration value="D103"/>
 *     &lt;enumeration value="D104"/>
 *     &lt;enumeration value="D105"/>
 *     &lt;enumeration value="D201"/>
 *     &lt;enumeration value="D202"/>
 *     &lt;enumeration value="D203"/>
 *     &lt;enumeration value="D204"/>
 *     &lt;enumeration value="D205"/>
 *     &lt;enumeration value="D206"/>
 *     &lt;enumeration value="D207"/>
 *     &lt;enumeration value="D301"/>
 *     &lt;enumeration value="D302"/>
 *     &lt;enumeration value="D303"/>
 *     &lt;enumeration value="D304"/>
 *     &lt;enumeration value="D305"/>
 *     &lt;enumeration value="D306"/>
 *     &lt;enumeration value="D307"/>
 *     &lt;enumeration value="D308"/>
 *     &lt;enumeration value="D309"/>
 *     &lt;enumeration value="D310"/>
 *     &lt;enumeration value="D311"/>
 *     &lt;enumeration value="D312"/>
 *     &lt;enumeration value="D313"/>
 *     &lt;enumeration value="D314"/>
 *     &lt;enumeration value="D315"/>
 *     &lt;enumeration value="D316"/>
 *     &lt;enumeration value="E100"/>
 *     &lt;enumeration value="E101"/>
 *     &lt;enumeration value="E102"/>
 *     &lt;enumeration value="E103"/>
 *     &lt;enumeration value="E104"/>
 *     &lt;enumeration value="E105"/>
 *     &lt;enumeration value="E106"/>
 *     &lt;enumeration value="E107"/>
 *     &lt;enumeration value="E108"/>
 *     &lt;enumeration value="E109"/>
 *     &lt;enumeration value="E110"/>
 *     &lt;enumeration value="E111"/>
 *     &lt;enumeration value="E112"/>
 *     &lt;enumeration value="E113"/>
 *     &lt;enumeration value="E114"/>
 *     &lt;enumeration value="E115"/>
 *     &lt;enumeration value="E116"/>
 *     &lt;enumeration value="E117"/>
 *     &lt;enumeration value="E118"/>
 *     &lt;enumeration value="E119"/>
 *     &lt;enumeration value="E120"/>
 *     &lt;enumeration value="E121"/>
 *     &lt;enumeration value="E122"/>
 *     &lt;enumeration value="E123"/>
 *     &lt;enumeration value="E124"/>
 *     &lt;enumeration value="E125"/>
 *     &lt;enumeration value="E126"/>
 *     &lt;enumeration value="E127"/>
 *     &lt;enumeration value="E128"/>
 *     &lt;enumeration value="E129"/>
 *     &lt;enumeration value="E130"/>
 *     &lt;enumeration value="E131"/>
 *     &lt;enumeration value="E132"/>
 *     &lt;enumeration value="E133"/>
 *     &lt;enumeration value="E134"/>
 *     &lt;enumeration value="E135"/>
 *     &lt;enumeration value="E136"/>
 *     &lt;enumeration value="E139"/>
 *     &lt;enumeration value="E140"/>
 *     &lt;enumeration value="E141"/>
 *     &lt;enumeration value="E142"/>
 *     &lt;enumeration value="E143"/>
 *     &lt;enumeration value="E144"/>
 *     &lt;enumeration value="E145"/>
 *     &lt;enumeration value="E200"/>
 *     &lt;enumeration value="E201"/>
 *     &lt;enumeration value="E202"/>
 *     &lt;enumeration value="E203"/>
 *     &lt;enumeration value="E204"/>
 *     &lt;enumeration value="E210"/>
 *     &lt;enumeration value="E211"/>
 *     &lt;enumeration value="E221"/>
 *     &lt;enumeration value="E222"/>
 *     &lt;enumeration value="E223"/>
 *     &lt;enumeration value="E224"/>
 *     &lt;enumeration value="E225"/>
 *     &lt;enumeration value="L101"/>
 *     &lt;enumeration value="P101"/>
 *     &lt;enumeration value="P102"/>
 *     &lt;enumeration value="P103"/>
 *     &lt;enumeration value="P104"/>
 *     &lt;enumeration value="P105"/>
 *     &lt;enumeration value="P106"/>
 *     &lt;enumeration value="P107"/>
 *     &lt;enumeration value="P108"/>
 *     &lt;enumeration value="P109"/>
 *     &lt;enumeration value="P110"/>
 *     &lt;enumeration value="P111"/>
 *     &lt;enumeration value="P112"/>
 *     &lt;enumeration value="P113"/>
 *     &lt;enumeration value="P114"/>
 *     &lt;enumeration value="P120"/>
 *     &lt;enumeration value="P201"/>
 *     &lt;enumeration value="P202"/>
 *     &lt;enumeration value="P203"/>
 *     &lt;enumeration value="P204"/>
 *     &lt;enumeration value="P301"/>
 *     &lt;enumeration value="V201"/>
 *     &lt;enumeration value="V202"/>
 *     &lt;enumeration value="V203"/>
 *     &lt;enumeration value="V220"/>
 *     &lt;enumeration value="V221"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List175")
@XmlEnum
public enum List175 {


    /**
     * CD ‘red book’ format
     * 
     */
    @XmlEnumValue("A101")
    A_101("A101"),
    @XmlEnumValue("A102")
    A_102("A102"),

    /**
     * MPEG-1/2 Audio Layer III file
     * 
     */
    @XmlEnumValue("A103")
    A_103("A103"),
    @XmlEnumValue("A104")
    A_104("A104"),
    @XmlEnumValue("A105")
    A_105("A105"),

    /**
     * Windows Media Audio format
     * 
     */
    @XmlEnumValue("A106")
    A_106("A106"),

    /**
     * Advanced Audio Coding format
     * 
     */
    @XmlEnumValue("A107")
    A_107("A107"),

    /**
     * Vorbis audio format in the Ogg container
     * 
     */
    @XmlEnumValue("A108")
    A_108("A108"),

    /**
     * Audio format proprietary to Audible.com
     * 
     */
    @XmlEnumValue("A109")
    A_109("A109"),

    /**
     * Free lossless audio codec
     * 
     */
    @XmlEnumValue("A110")
    A_110("A110"),

    /**
     * Audio Interchangeable File Format
     * 
     */
    @XmlEnumValue("A111")
    A_111("A111"),

    /**
     * Apple Lossless Audio Codec
     * 
     */
    @XmlEnumValue("A112")
    A_112("A112"),

    /**
     * Deprecated, as does not meet DAISY 2 standard. Use conventional audiobook codes instead
     * 
     */
    @XmlEnumValue("A201")
    A_201("A201"),
    @XmlEnumValue("A202")
    A_202("A202"),
    @XmlEnumValue("A203")
    A_203("A203"),
    @XmlEnumValue("A204")
    A_204("A204"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A205")
    A_205("A205"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A206")
    A_206("A206"),

    /**
     * Deprecated, as does not meet DAISY 3 standard. Use conventional audiobook codes instead
     * 
     */
    @XmlEnumValue("A207")
    A_207("A207"),
    @XmlEnumValue("A208")
    A_208("A208"),
    @XmlEnumValue("A209")
    A_209("A209"),
    @XmlEnumValue("A210")
    A_210("A210"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A211")
    A_211("A211"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A212")
    A_212("A212"),
    @XmlEnumValue("A301")
    A_301("A301"),

    /**
     * Audio intended exclusively for use alongside a printed copy of the book. Most often a children’s product. Normally contains instructions such as ‘turn the page now’ and other references to the printed item, and is usually sold packaged together with a printed copy
     * 
     */
    @XmlEnumValue("A302")
    A_302("A302"),

    /**
     * Audio intended for musical accompaniment, eg ‘Music minus one’, etc, often used for music learning. Includes singalong backing audio for musical learning or for Karaoke-style entertainment
     * 
     */
    @XmlEnumValue("A303")
    A_303("A303"),

    /**
     * Audio intended for language learning, which includes speech plus gaps intended to be filled by the listener
     * 
     */
    @XmlEnumValue("A304")
    A_304("A304"),

    /**
     * Audio synchronised to text within an e-publication, for example an EPUB3 with audio overlay. Synchronisation at least at paragraph level, and covering the full content
     * 
     */
    @XmlEnumValue("A305")
    A_305("A305"),

    /**
     * Includes 'stereo' where channels are identical
     * 
     */
    @XmlEnumValue("A410")
    A_410("A410"),
    @XmlEnumValue("A420")
    A_420("A420"),

    /**
     * Stereo plus low-frequency channel
     * 
     */
    @XmlEnumValue("A421")
    A_421("A421"),

    /**
     * Five-channel audio (including low-frequency channel)
     * 
     */
    @XmlEnumValue("A441")
    A_441("A441"),

    /**
     * Six-channel audio (including low-frequency channel)
     * 
     */
    @XmlEnumValue("A451")
    A_451("A451"),

    /**
     * In North America, a category of paperback characterized partly by page size (typically 4¼ x 7 1/8 inches) and partly by target market and terms of trade. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B101")
    B_101("B101"),

    /**
     * In North America, a category of paperback characterized partly by page size and partly by target market and terms of trade. AKA ‘quality paperback’, and including textbooks. Most paperback books sold in North America except ‘mass-market’ (B101) and ‘tall rack’ (B107) are correctly described with this code. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B102")
    B_102("B102"),

    /**
     * In North America, a category of paperback characterized by page size and generally used for children’s books; use with Product Form code BC. Note: was wrongly shown as B102 (duplicate entry) in Issue 3
     * 
     */
    @XmlEnumValue("B103")
    B_103("B103"),

    /**
     * In UK, a category of paperback characterized by page size (normally 178 x 111 mm approx); use with Product Form code BC
     * 
     */
    @XmlEnumValue("B104")
    B_104("B104"),

    /**
     * In UK, a category of paperback characterized by page size (normally 198 x 129 mm approx); use with Product Form code BC
     * 
     */
    @XmlEnumValue("B105")
    B_105("B105"),

    /**
     * In UK, a category of paperback characterized partly by size (usually in traditional hardback dimensions), and often used for paperback originals; use with Product Form code BC (replaces ‘C-format’ from former List 8)
     * 
     */
    @XmlEnumValue("B106")
    B_106("B106"),

    /**
     * In North America, a category of paperback characterised partly by page size and partly by target market and terms of trade; use with Product Form code BC
     * 
     */
    @XmlEnumValue("B107")
    B_107("B107"),

    /**
     *  210x148mm
     * 
     */
    @XmlEnumValue("B108")
    B_108("B108"),

    /**
     * Japanese B-series size, 257x182mm
     * 
     */
    @XmlEnumValue("B109")
    B_109("B109"),

    /**
     * Japanese B-series size, 182x128mm
     * 
     */
    @XmlEnumValue("B110")
    B_110("B110"),

    /**
     *  148x105mm
     * 
     */
    @XmlEnumValue("B111")
    B_111("B111"),

    /**
     * Japanese format, 182x103mm or 173x105mm
     * 
     */
    @XmlEnumValue("B112")
    B_112("B112"),

    /**
     * A Swedish, Norwegian, French paperback format, of no particular fixed size. Use with Product Form Code BC
     * 
     */
    @XmlEnumValue("B113")
    B_113("B113"),

    /**
     * A Swedish paperback format, use with Product Form Code BC
     * 
     */
    @XmlEnumValue("B114")
    B_114("B114"),

    /**
     * A Swedish hardback format, use with Product Form Code BB
     * 
     */
    @XmlEnumValue("B115")
    B_115("B115"),

    /**
     * A Swedish softback format, use with Product Form Code BC
     * 
     */
    @XmlEnumValue("B116")
    B_116("B116"),

    /**
     * A softback book in the format of a magazine, usually sold like a book. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B117")
    B_117("B117"),

    /**
     * Also called ‘Flipback’. A softback book in a specially compact proprietary format with pages printed in landscape on very thin paper and bound along the long (top) edge – see www.dwarsligger.com
     * 
     */
    @XmlEnumValue("B118")
    B_118("B118"),

    /**
     * Japanese format: 188x127mm
     * 
     */
    @XmlEnumValue("B119")
    B_119("B119"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B120")
    B_120("B120"),

    /**
     *  297x210mm
     * 
     */
    @XmlEnumValue("B121")
    B_121("B121"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B122")
    B_122("B122"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B123")
    B_123("B123"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B124")
    B_124("B124"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B125")
    B_125("B125"),

    /**
     *  257x210mm
     * 
     */
    @XmlEnumValue("B126")
    B_126("B126"),

    /**
     * Japanese B-series size, 128x91mm
     * 
     */
    @XmlEnumValue("B127")
    B_127("B127"),

    /**
     * Japanese format: 218x152mm or 227x152mm
     * 
     */
    @XmlEnumValue("B128")
    B_128("B128"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B129")
    B_129("B129"),

    /**
     * Japanese B-series size, 257x364mm
     * 
     */
    @XmlEnumValue("B130")
    B_130("B130"),

    /**
     * German paperback format, greater than 205mm high, with flaps. Use with Product form code BC
     * 
     */
    @XmlEnumValue("B131")
    B_131("B131"),
    @XmlEnumValue("B201")
    B_201("B201"),
    @XmlEnumValue("B202")
    B_202("B202"),

    /**
     * Note: was wrongly shown as B203 (duplicate entry) in Issue 3
     * 
     */
    @XmlEnumValue("B204")
    B_204("B204"),
    @XmlEnumValue("B205")
    B_205("B205"),
    @XmlEnumValue("B206")
    B_206("B206"),
    @XmlEnumValue("B207")
    B_207("B207"),
    @XmlEnumValue("B208")
    B_208("B208"),
    @XmlEnumValue("B209")
    B_209("B209"),

    /**
     * A book whose pages have a variety of textured inserts designed to stimulate tactile exploration: see also B214 and B215
     * 
     */
    @XmlEnumValue("B210")
    B_210("B210"),

    /**
     * A book which is cut into a distinctive non-rectilinear shape and/or in which holes or shapes have been cut internally. (‘Die-cut’ is used here as a convenient shorthand, and does not imply strict limitation to a particular production process)
     * 
     */
    @XmlEnumValue("B212")
    B_212("B212"),

    /**
     * A book which is also a toy, or which incorporates a toy as an integral part. (Do not, however, use B213 for a multiple-item product which includes a book and a toy as separate items)
     * 
     */
    @XmlEnumValue("B213")
    B_213("B213"),

    /**
     * A book whose cover has a soft textured finish, typically over board
     * 
     */
    @XmlEnumValue("B214")
    B_214("B214"),

    /**
     * A book with detachable felt pieces and textured pages on which they can be arranged
     * 
     */
    @XmlEnumValue("B215")
    B_215("B215"),

    /**
     * Children’s picture book: use with applicable Product Form code
     * 
     */
    @XmlEnumValue("B221")
    B_221("B221"),

    /**
     * (aka ‘Star’ book). Tax treatment of products may differ from that of products with similar codes such as Book as toy or Pop-up book)
     * 
     */
    @XmlEnumValue("B222")
    B_222("B222"),

    /**
     * A book with movable card 'tabs' within the pages. Pull a tab to reveal or animate part of a picture (distinct from a ‘lift-the-flap’ book, where flaps simply reveal hidden pictures, and from a ‘pop-up’ book with 3D paper engineering)
     * 
     */
    @XmlEnumValue("B223")
    B_223("B223"),

    /**
     * Use with Product Form code BD
     * 
     */
    @XmlEnumValue("B301")
    B_301("B301"),

    /**
     * Use with Product Form code BD
     * 
     */
    @XmlEnumValue("B302")
    B_302("B302"),

    /**
     * Use with Product Form code BD
     * 
     */
    @XmlEnumValue("B303")
    B_303("B303"),

    /**
     * AKA stitched; for ‘saddle-sewn’, see code B310
     * 
     */
    @XmlEnumValue("B304")
    B_304("B304"),

    /**
     * Including ‘perfect bound’, ‘glued’
     * 
     */
    @XmlEnumValue("B305")
    B_305("B305"),

    /**
     * Strengthened cloth-over-boards binding intended for libraries: use with Product form code BB
     * 
     */
    @XmlEnumValue("B306")
    B_306("B306"),

    /**
     * Strengthened binding, not specifically intended for libraries: use with Product form code BB or BC
     * 
     */
    @XmlEnumValue("B307")
    B_307("B307"),

    /**
     * Must be accompanied by a code specifiying a material, eg ‘half-bound real leather’
     * 
     */
    @XmlEnumValue("B308")
    B_308("B308"),

    /**
     * Must be accompanied by a code specifiying a material, eg ‘quarter bound real leather’
     * 
     */
    @XmlEnumValue("B309")
    B_309("B309"),

    /**
     * AKA ‘saddle-stitched’ or ‘wire-stitched’
     * 
     */
    @XmlEnumValue("B310")
    B_310("B310"),

    /**
     * Round or oval plastic forms in a clamp-like configuration: use with Product Form code BE
     * 
     */
    @XmlEnumValue("B311")
    B_311("B311"),

    /**
     * Twin loop metal wire spine: use with Product Form code BE
     * 
     */
    @XmlEnumValue("B312")
    B_312("B312"),

    /**
     * Cased over Coiled or Wire-O binding: use with Product Form code BE and Product Form Detail code B312 or B315
     * 
     */
    @XmlEnumValue("B313")
    B_313("B313"),

    /**
     * Spiral wire bound. Use with product form code BE. The default if a spiral binding type is not stated. Cf. Comb and Wire-O binding
     * 
     */
    @XmlEnumValue("B314")
    B_314("B314"),

    /**
     * Hardcover binding intended for general consumers rather than libraries, use with Product form code BB. The default if a hardcover binding detail is not stated. cf. Library binding
     * 
     */
    @XmlEnumValue("B315")
    B_315("B315"),

    /**
     * Cover is attached to the book block along only one edge of the spine, allowing the cover to lay flat
     * 
     */
    @XmlEnumValue("B316")
    B_316("B316"),

    /**
     * Refinement of perfect binding, with notches cut in the spine of the book block prior to glueing, to improve adhesion and durability
     * 
     */
    @XmlEnumValue("B317")
    B_317("B317"),

    /**
     * Covers do not use a distinctive stock, but are the same as the body pages
     * 
     */
    @XmlEnumValue("B400")
    B_400("B400"),

    /**
     * AKA fabric, linen over boards
     * 
     */
    @XmlEnumValue("B401")
    B_401("B401"),
    @XmlEnumValue("B402")
    B_402("B402"),
    @XmlEnumValue("B403")
    B_403("B403"),
    @XmlEnumValue("B404")
    B_404("B404"),
    @XmlEnumValue("B405")
    B_405("B405"),
    @XmlEnumValue("B406")
    B_406("B406"),

    /**
     * Cloth, not necessarily over boards – cf B401
     * 
     */
    @XmlEnumValue("B409")
    B_409("B409"),

    /**
     * Spanish ‘simil-tela’
     * 
     */
    @XmlEnumValue("B410")
    B_410("B410"),
    @XmlEnumValue("B411")
    B_411("B411"),

    /**
     * AKA ‘flexibound’: use with Product Form code BC
     * 
     */
    @XmlEnumValue("B412")
    B_412("B412"),
    @XmlEnumValue("B413")
    B_413("B413"),
    @XmlEnumValue("B414")
    B_414("B414"),

    /**
     * Book, laminating material unspecified: use L101 for ‘whole product laminated’, eg a laminated sheet map or wallchart
     * 
     */
    @XmlEnumValue("B415")
    B_415("B415"),

    /**
     * With card cover (like a typical paperback). As distinct from a self-cover or more elaborate binding
     * 
     */
    @XmlEnumValue("B416")
    B_416("B416"),

    /**
     * Type unspecified
     * 
     */
    @XmlEnumValue("B501")
    B_501("B501"),

    /**
     * Used to distinguish from B503
     * 
     */
    @XmlEnumValue("B502")
    B_502("B502"),

    /**
     * With translucent paper or plastic protective cover
     * 
     */
    @XmlEnumValue("B503")
    B_503("B503"),

    /**
     * For paperback with flaps
     * 
     */
    @XmlEnumValue("B504")
    B_504("B504"),
    @XmlEnumValue("B505")
    B_505("B505"),

    /**
     * If the number of markers is significant, it can be stated as free text in <ProductFormDescription>
     * 
     */
    @XmlEnumValue("B506")
    B_506("B506"),
    @XmlEnumValue("B507")
    B_507("B507"),
    @XmlEnumValue("B508")
    B_508("B508"),

    /**
     * AKA yapp edge?
     * 
     */
    @XmlEnumValue("B509")
    B_509("B509"),

    /**
     * With edge trimming such that the front edge is ragged, not neatly and squarely trimmed: AKA deckle edge, feather edge, uncut edge, rough cut
     * 
     */
    @XmlEnumValue("B510")
    B_510("B510"),

    /**
     * With one or more gatefold or foldout sections bound in
     * 
     */
    @XmlEnumValue("B511")
    B_511("B511"),

    /**
     * Pages include extra-wide margin specifically intended for hand-written annotations
     * 
     */
    @XmlEnumValue("B512")
    B_512("B512"),

    /**
     * Book with attached loop for fixing to baby stroller, cot, chair etc
     * 
     */
    @XmlEnumValue("B513")
    B_513("B513"),

    /**
     * With one or more pages perforated and intended to be torn out for use
     * 
     */
    @XmlEnumValue("B514")
    B_514("B514"),

    /**
     * Printed on acid-free or alkaline buffered paper conforming with ISO 9706
     * 
     */
    @XmlEnumValue("B515")
    B_515("B515"),

    /**
     * Printed on acid-free or alkaline buffered paper with a high cotton content, conforming with ISO 11108
     * 
     */
    @XmlEnumValue("B516")
    B_516("B516"),

    /**
     * A book in which half the content is printed upside-down, to be read the other way round. Also known as a ‘flip-book’, ‘back-to-back’, (fr.) ‘tête-bêche’ (usually an omnibus of two works)
     * 
     */
    @XmlEnumValue("B601")
    B_601("B601"),

    /**
     * Manga with pages and panels in the sequence of the original Japanese, but with Western text
     * 
     */
    @XmlEnumValue("B602")
    B_602("B602"),

    /**
     * Text shows syllable breaks
     * 
     */
    @XmlEnumValue("B610")
    B_610("B610"),

    /**
     * Single letters only. Was formerly identified as UK Braille Grade 1
     * 
     */
    @XmlEnumValue("B701")
    B_701("B701"),

    /**
     * With some letter combinations. Was formerly identified as UK Braille Grade 2
     * 
     */
    @XmlEnumValue("B702")
    B_702("B702"),

    /**
     * DEPRECATED- use B704/B705 as appropriate instead
     * 
     */
    @XmlEnumValue("B703")
    B_703("B703"),
    @XmlEnumValue("B704")
    B_704("B704"),
    @XmlEnumValue("B705")
    B_705("B705"),
    @XmlEnumValue("B706")
    B_706("B706"),

    /**
     * Moon embossed alphabet, used by some print-impaired readers who have difficulties with Braille
     * 
     */
    @XmlEnumValue("B707")
    B_707("B707"),

    /**
     * Proprietary RealNetworks format. Includes Real Video packaged within a .rm RealMedia container
     * 
     */
    @XmlEnumValue("D101")
    D_101("D101"),
    @XmlEnumValue("D102")
    D_102("D102"),
    @XmlEnumValue("D103")
    D_103("D103"),
    @XmlEnumValue("D104")
    D_104("D104"),
    @XmlEnumValue("D105")
    D_105("D105"),

    /**
     * Use with an applicable Product Form code D*; note that more detail of operating system requirements can be given in a Product Form Feature composite
     * 
     */
    @XmlEnumValue("D201")
    D_201("D201"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D202")
    D_202("D202"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D203")
    D_203("D203"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D204")
    D_204("D204"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D205")
    D_205("D205"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D206")
    D_206("D206"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D207")
    D_207("D207"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D301")
    D_301("D301"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D302")
    D_302("D302"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D303")
    D_303("D303"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D304")
    D_304("D304"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D305")
    D_305("D305"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D306")
    D_306("D306"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D307")
    D_307("D307"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D308")
    D_308("D308"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D309")
    D_309("D309"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D310")
    D_310("D310"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D311")
    D_311("D311"),
    @XmlEnumValue("D312")
    D_312("D312"),
    @XmlEnumValue("D313")
    D_313("D313"),
    @XmlEnumValue("D314")
    D_314("D314"),
    @XmlEnumValue("D315")
    D_315("D315"),
    @XmlEnumValue("D316")
    D_316("D316"),

    /**
     * No code allocated for this e-publication format yet
     * 
     */
    @XmlEnumValue("E100")
    E_100("E100"),

    /**
     * The Open Publication Structure / OPS Container Format standard of the International Digital Publishing Forum (IDPF) [File extension .epub]
     * 
     */
    @XmlEnumValue("E101")
    E_101("E101"),

    /**
     * The Open EBook format of the IDPF, a predecessor of the full EPUB format, still (2008) supported as part of the latter [File extension .opf]. Includes EPUB format up to and including version 2 – but prefer code E101 for EPUB 2, and always use code E101 for EPUB 3
     * 
     */
    @XmlEnumValue("E102")
    E_102("E102"),

    /**
     * Microsoft Word binary document format [File extension .doc]
     * 
     */
    @XmlEnumValue("E103")
    E_103("E103"),

    /**
     * Office Open XML / Microsoft Word XML document format (ISO/IEC 29500:2008) [File extension .docx]
     * 
     */
    @XmlEnumValue("E104")
    E_104("E104"),

    /**
     * HyperText Mark-up Language [File extension .html, .htm]
     * 
     */
    @XmlEnumValue("E105")
    E_105("E105"),

    /**
     * Open Document Format [File extension .odt]
     * 
     */
    @XmlEnumValue("E106")
    E_106("E106"),

    /**
     * Portable Document Format (ISO 32000-1:2008) [File extension .pdf]
     * 
     */
    @XmlEnumValue("E107")
    E_107("E107"),

    /**
     * PDF archiving format defined by ISO 19005-1:2005 [File extension .pdf]
     * 
     */
    @XmlEnumValue("E108")
    E_108("E108"),

    /**
     * Rich Text Format [File extension .rtf]
     * 
     */
    @XmlEnumValue("E109")
    E_109("E109"),

    /**
     * Standard Generalized Mark-up Language
     * 
     */
    @XmlEnumValue("E110")
    E_110("E110"),

    /**
     * A compressed text format mainly used on Psion handheld devices [File extension .tcr]
     * 
     */
    @XmlEnumValue("E111")
    E_111("E111"),

    /**
     * Text file format [File extension .txt]. Typically ASCII or Unicode UTF-8/16
     * 
     */
    @XmlEnumValue("E112")
    E_112("E112"),

    /**
     * Extensible Hypertext Markup Language [File extension .xhtml, .xht, .xml, .html, .htm]
     * 
     */
    @XmlEnumValue("E113")
    E_113("E113"),

    /**
     * A compressed text format mainly used on Palm handheld devices [File extension .pdb – see also E121, E125, E130]
     * 
     */
    @XmlEnumValue("E114")
    E_114("E114"),

    /**
     * XML Paper Specification format [File extension .xps]
     * 
     */
    @XmlEnumValue("E115")
    E_115("E115"),

    /**
     * A format proprietary to Amazon for use with its Kindle reading devices or software readers [File extensions .azw, .mobi, .prc]
     * 
     */
    @XmlEnumValue("E116")
    E_116("E116"),

    /**
     * A Sony proprietary format for use with the Sony Reader and LIBRIé reading devices [File extension .lrf]
     * 
     */
    @XmlEnumValue("E117")
    E_117("E117"),

    /**
     * A proprietary format for use with DXReader software
     * 
     */
    @XmlEnumValue("E118")
    E_118("E118"),

    /**
     * A format proprietary to the Ebook Library service
     * 
     */
    @XmlEnumValue("E119")
    E_119("E119"),

    /**
     * A format proprietary to the Ebrary service
     * 
     */
    @XmlEnumValue("E120")
    E_120("E120"),

    /**
     * A proprietary format for use with eReader (AKA ‘Palm Reader’) software on various hardware platforms [File extension .pdb – see also E114, E125, E130]
     * 
     */
    @XmlEnumValue("E121")
    E_121("E121"),

    /**
     * A proprietary format with its own reading system for Windows platforms [File extension .exe]
     * 
     */
    @XmlEnumValue("E122")
    E_122("E122"),

    /**
     * A proprietary format for use with the Franklin eBookman reader
     * 
     */
    @XmlEnumValue("E123")
    E_123("E123"),

    /**
     * A proprietary format for use with the Gemstar Rocketbook reader [File extension .rb]
     * 
     */
    @XmlEnumValue("E124")
    E_124("E124"),

    /**
     * A proprietary format for use with iSilo software on various hardware platforms [File extension .pdb – see also E114, E121, E130]
     * 
     */
    @XmlEnumValue("E125")
    E_125("E125"),

    /**
     * A proprietary format for use with Microsoft Reader software on Windows and Pocket PC platforms [File extension .lit]
     * 
     */
    @XmlEnumValue("E126")
    E_126("E126"),

    /**
     * A proprietary format for use with Mobipocket software on various hardware platforms [File extensions .mobi, .prc]. Includes Amazon Kindle formats up to and including version 7 – but prefer code E116 for version 7, and always use E116 for KF8
     * 
     */
    @XmlEnumValue("E127")
    E_127("E127"),

    /**
     * A format proprietary to the MyiLibrary service
     * 
     */
    @XmlEnumValue("E128")
    E_128("E128"),

    /**
     * A format proprietary to the NetLibrary service
     * 
     */
    @XmlEnumValue("E129")
    E_129("E129"),

    /**
     * A proprietary format for use with Plucker reader software on Palm and other handheld devices [File extension .pdb – see also E114, E121, E125]
     * 
     */
    @XmlEnumValue("E130")
    E_130("E130"),

    /**
     * A format proprietary to the VitalSource service
     * 
     */
    @XmlEnumValue("E131")
    E_131("E131"),

    /**
     * A proprietary digital product combining text and video content and available to be used online or as a downloadable application for a mobile device – see www.vook.com
     * 
     */
    @XmlEnumValue("E132")
    E_132("E132"),

    /**
     * An epublication made available by Google in association with a publisher; readable online on a browser-enabled device and offline on designated ebook readers
     * 
     */
    @XmlEnumValue("E133")
    E_133("E133"),

    /**
     * Epublication packaged as application for iOS (eg Apple iPhone, iPad etc), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements
     * 
     */
    @XmlEnumValue("E134")
    E_134("E134"),

    /**
     * Epublication packaged as application for Android (eg Android phone or tablet), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements
     * 
     */
    @XmlEnumValue("E135")
    E_135("E135"),

    /**
     * Epublication packaged as application, containing both executable code and content. Use where other ‘app’ codes are not applicable. Technical requirements such as target operating system and/or device should be provided eg in <ProductFormFeatureType>. Content type (text or text plus various ‘enhancements’) may be described with <ProductContentType>
     * 
     */
    @XmlEnumValue("E136")
    E_136("E136"),

    /**
     * Founder Apabi’s proprietary basic e-book format
     * 
     */
    @XmlEnumValue("E139")
    E_139("E139"),

    /**
     * Founder Apabi’s proprietary XML e-book format
     * 
     */
    @XmlEnumValue("E140")
    E_140("E140"),

    /**
     * Apple’s iBook format (a proprietary extension of EPUB), can only be read on Apple iOS devices
     * 
     */
    @XmlEnumValue("E141")
    E_141("E141"),

    /**
     * Proprietary format based on EPUB used by Barnes and Noble for fixed-format e-books, readable on NOOK devices and Nook reader software
     * 
     */
    @XmlEnumValue("E142")
    E_142("E142"),

    /**
     * Sharable Content Object Reference Model, standard content and packaging format for e-learning objects
     * 
     */
    @XmlEnumValue("E143")
    E_143("E143"),

    /**
     * E-book Plus (proprietary Norwegian e-book format)
     * 
     */
    @XmlEnumValue("E144")
    E_144("E144"),

    /**
     * Proprietary format based on PDF used by Barnes and Noble for fixed-format e-books, readable on some NOOK devices and Nook reader software
     * 
     */
    @XmlEnumValue("E145")
    E_145("E145"),

    /**
     * Use when a particular e-publication type (specified using codes E100 and upwards) has both fixed format and reflowable variants
     * 
     */
    @XmlEnumValue("E200")
    E_200("E200"),

    /**
     * Use when a particular e-publication type (specified using codes E100 and upwards) has both fixed format and reflowable variants
     * 
     */
    @XmlEnumValue("E201")
    E_201("E201"),

    /**
     * All e-publication resources are included within the e-publication package
     * 
     */
    @XmlEnumValue("E202")
    E_202("E202"),

    /**
     * E-publication requires a network connection to access some resources (eg an enhanced e-book where video clips are not stored within the e-publication package itself, but are delivered via an internet connection)
     * 
     */
    @XmlEnumValue("E203")
    E_203("E203"),

    /**
     * Resources (eg images) present in other editions have been removed from this product, eg due to rights issues
     * 
     */
    @XmlEnumValue("E204")
    E_204("E204"),

    /**
     * Use for fixed-format e-books optimised for landscape display. Also include an indication of the optimal screen aspect ratio
     * 
     */
    @XmlEnumValue("E210")
    E_210("E210"),

    /**
     * Use for fixed-format e-books optimised for portrait display. Also include an indication of the optimal screen aspect ratio
     * 
     */
    @XmlEnumValue("E211")
    E_211("E211"),

    /**
     * Use for fixed-format e-books optimised for displays with a 5:4 aspect ratio (eg 1280x1024 pixels etc, assuming square pixels). Note that aspect ratio codes are NOT specific to actual screen dimensions or pixel counts, but to the ratios between two dimensions or two pixel counts
     * 
     */
    @XmlEnumValue("E221")
    E_221("E221"),

    /**
     * Use for fixed-format e-books optimised for displays with a 4:3 aspect ratio (eg 800x600, 1024x768, 2048x1536 pixels etc)
     * 
     */
    @XmlEnumValue("E222")
    E_222("E222"),

    /**
     * Use for fixed-format e-books optimised for displays with a 3:2 aspect ratio (eg 960x640, 3072x2048 pixels etc)
     * 
     */
    @XmlEnumValue("E223")
    E_223("E223"),

    /**
     * Use for fixed-format e-books optimised for displays with a 16:10 aspect ratio (eg 1440x900, 2560x1600 pixels etc)
     * 
     */
    @XmlEnumValue("E224")
    E_224("E224"),

    /**
     * Use for fixed-format e-books optimised for displays with a 16:9 aspect ratio (eg 1024x576, 1920x1080, 2048x1152 pixels etc)
     * 
     */
    @XmlEnumValue("E225")
    E_225("E225"),

    /**
     * Whole product laminated (eg laminated map, fold-out chart, wallchart, etc): use B415 for book with laminated cover
     * 
     */
    @XmlEnumValue("L101")
    L_101("L101"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P101")
    P_101("P101"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P102")
    P_102("P102"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P103")
    P_103("P103"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P104")
    P_104("P104"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P105")
    P_105("P105"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P106")
    P_106("P106"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P107")
    P_107("P107"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P108")
    P_108("P108"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P109")
    P_109("P109"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P110")
    P_110("P110"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P111")
    P_111("P111"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P112")
    P_112("P112"),

    /**
     * A calendar that is not one of the types specified elsewhere: use with Product Form code PC
     * 
     */
    @XmlEnumValue("P113")
    P_113("P113"),

    /**
     * A product that is associated with or ancillary to a calendar or organiser, eg a deskstand for a calendar, or an insert for an organiser: use with Product Form code PC or PS
     * 
     */
    @XmlEnumValue("P114")
    P_114("P114"),

    /**
     * Kamishibai / Cantastoria cards
     * 
     */
    @XmlEnumValue("P120")
    P_120("P120"),

    /**
     * Stationery item in hardback book format
     * 
     */
    @XmlEnumValue("P201")
    P_201("P201"),

    /**
     * Stationery item in paperback/softback book format
     * 
     */
    @XmlEnumValue("P202")
    P_202("P202"),

    /**
     * Stationery item in spiral-bound book format
     * 
     */
    @XmlEnumValue("P203")
    P_203("P203"),

    /**
     * Stationery item in leather-bound book format, or other fine binding
     * 
     */
    @XmlEnumValue("P204")
    P_204("P204"),

    /**
     * For wall map, poster, wallchart etc
     * 
     */
    @XmlEnumValue("P301")
    P_301("P301"),

    /**
     * TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V201")
    V_201("V201"),

    /**
     * TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V202")
    V_202("V202"),

    /**
     * TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V203")
    V_203("V203"),

    /**
     * Licensed for use in domestic contexts only
     * 
     */
    @XmlEnumValue("V220")
    V_220("V220"),

    /**
     * Licensed for use in education
     * 
     */
    @XmlEnumValue("V221")
    V_221("V221");
    private final String value;

    List175(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List175 fromValue(String v) {
        for (List175 c: List175 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
