//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 07:39:09 PM IST 
//


package onix.social.logos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List224.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List224">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="Q"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="F"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List224")
@XmlEnum
public enum List224 {


    /**
     * Use ONLY if the message severity cannot be determined (eg with a legacy system unable to provide detailed error codes)
     * 
     */
    U,

    /**
     * For information only, provided to encourage the ONIX data supplier to improve the quality of their data (eg provision of a non-mandatory data element that is currently missing, better conformity with best practice, etc)
     * 
     */
    I,

    /**
     * Request for clarification or further detail of the meaning of the data provided
     * 
     */
    Q,

    /**
     * The ONIX data has been accepted as provided, but there may be issues in the way it is supplied
     * 
     */
    W,

    /**
     * Some data in an ONIX data element or message structure caused an error due to not meeting the requirements of the standard. The data in question has been rejected, but processing of the remaining elements in the record (or the remain records in the message, if used within <MessageStatusDetail>) has continued
     * 
     */
    E,

    /**
     * Some data in an ONIX data element or message structure caused an unrecoverable error due to not meeting the requirements of the standard. The entire ONIX record has been rejected (or the entire message, if used within <MessageStatusDetail>)
     * 
     */
    F;

    public String value() {
        return name();
    }

    public static List224 fromValue(String v) {
        return valueOf(v);
    }

}
