//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 07:39:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.editeur.org/onix/3.0/reference", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package onix.social.logos;
